### ISSUE TITLE
The minimum viable code doesn't run through

### ISSUE THREAD

**Issue by ManuFU** [dpanagop/re-identification#1]
![image](https://user-images.githubusercontent.com/15906404/113676135-62c49300-96bc-11eb-9c38-1dc769203646.png)

**Comment by dpanagop** [comment]
It is because the code is not for Tensorflow v2. You can try using
```python
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
instead of 
```python
import tensorflow as tf
```

as explained here
https://stackoverflow.com/questions/57614436/od-graph-def-tf-graphdef-attributeerror-module-tensorflow-has-no-attribut

**Comment by dpanagop** [comment]
Closing issue based on the explanation given about tensorflow compatibility.
